### ISSUE TITLE
Label Suggestions

### ISSUE THREAD

**Issue by neversitdull** [SwiftCommunityPodcast/podcast#10]
It might be nice to create some new labels to help keep issues organized. 

For example: 

`suggestion - Episode/Topic Suggestions`
`feedback - General feedback`

Just a thought. 😁

**Comment by BasThomas** [comment]
Hi @neversitdull, there is now an "episode suggestion" label. I don't think we'll be needing a label for feedback... or at least I am not sure if we do, so I'll leave that as-is for now.

Thanks for the suggestions!
