### ISSUE TITLE
Would love to be a guest - Swift in Depth book author

### ISSUE THREAD

**Issue by tjeerdintveen** [SwiftCommunityPodcast/podcast#14]
Great job everybody, I enjoyed the first episode a lot, it makes my commute feel a lot shorter, and I would love to see where this podcast is headed!

It would be cool to be a guest. I am the author of Swift in Depth, published by Manning.  I have a lot of experience working with many developers and extracted common learning paths into a book.

 I'd love to talk about:

- Common learning patterns and hurdles that developers experience in their Swift careers and how to become a better Swift developer in a shorter time.
- Working with Swift at a larger scale, e.g. working with multiple international teams, splitting up Swift code into multiple frameworks, the challenges it brings.
- Hiring Swift developers and interviews.
- Swift in general 😃

I love how this podcast is "open source" and would be happy to help!

**Comment by garricn** [comment]
Thank you for letting us know! We're currently working with the community on creating an open source process for empowering people to contribute episodes. Once we figure that out, perhaps someone in the community (even you perhaps!) could create an episode proposal for this.

**Comment by tjeerdintveen** [comment]
Sounds good, thanks!
