### ISSUE TITLE
Podcast Song

### ISSUE THREAD

**Issue by ercillagorka** [SwiftCommunityPodcast/podcast#23]
I would like to collaborate to create a melody or song for the podcast. 
It would be interesting to do something similar to the intro song of @JohnSundell podcast (Swift by Sundell)

Thanks!

**Comment by garricn** [comment]
Do it! Feel free to open a Pull Request that adds the audio file to the Audio directory. 🚀

**Comment by garricn** [comment]
Any update on this? I can use the song for #22

**Comment by lattner** [comment]
Exciting!!
