### ISSUE TITLE
Topic Suggestion

### ISSUE THREAD

**Issue by AndrewLitteken** [SwiftCommunityPodcast/podcast#38]
There is a lot of talk about contributing to Swift.  But could there be a discussion in a future episode about what is a good way to actually help contribute Swift, which seems to be fairly fast moving. As someone new to (and aspiring to work in) language development and to contributing to open-source as a whole I think it would help people understand the process.

Potential Avenues:
-Picking a project/issue
-Finding help
-Navigating Past developments

**Comment by garricn** [comment]
This is a great idea! Would you be interested in producing this episode? I can help you.

**Comment by AndrewLitteken** [comment]
I would be interesting in producing it.  Which aspects of the podcast does being the producer entail?

**Comment by RJ-Clegg** [comment]
This is a really good idea.

**Comment by BasThomas** [comment]
I'm wondering if @theblixguy would be interested in jumping in here, as a contributor to Swift?!

**Comment by theblixguy** [comment]
I would be happy to talk about my journey and answer any questions!

**Comment by AndrewLitteken** [comment]
I created a proposal and pull request for the episode, @garricn can you let me know what the next best step is?

**Comment by AndrewLitteken** [comment]
Closing since the episode has been published!
