### ISSUE TITLE
Episodes do not have speed controls

### ISSUE THREAD

**Issue by Dante-Broggi** [SwiftCommunityPodcast/podcast#41]
I watch / listen to (almost) all online content at 2x speed. 
However, the Swift Community Podcast does not have speed controls, 
and also does not support:
```javascript 
document.querySelector("video").playbackRate = 2.0;
```
Or:
```javascript 
document.querySelector("audio").playbackRate = 2.0;
```

**Comment by marcusrossel** [comment]
Does this pertain to the swiftcommunitypodcast.org website, or are you talking about other players as well?

**Comment by JohnSundell** [comment]
@Dante-Broggi must mean the website, right? I suggest using a proper podcast player (the online player is really only there for the RSS feed) - such as Apple Podcasts or Overcast, both of which are free and offer speed controls.

**Comment by marcusrossel** [comment]
The overcast.fm website will also allow you to listen to your podcasts at variable speeds without having to use a seperate app.
