### ISSUE TITLE
How to link the episode 1 transcript from the shownotes?

### ISSUE THREAD

**Issue by ole** [SwiftCommunityPodcast/podcast#44]
I'd like to add a link to the [transcript](
https://github.com/SwiftCommunityPodcast/podcast/blob/master/Shownotes/Episode1-Transcript.vtt) ([now that it's merged](#43)) to the episode 1 shownotes. What URL do I have to use? How can we get the `.vtt` file on the webserver? What process do you use to build the website?

**Comment by marcusrossel** [comment]
Do you mean you want to add a link in the "NOTES"-section of the VTT-file that points to the shownotes?

**Comment by ole** [comment]
I mean that [the episode page on the website](https://www.swiftcommunitypodcast.org/episodes/1) should contain a link to the transcript. It seems to me that there's no direct link between the files in this repo and the HTML content on the webserver.

I originally assumed that the admin of the website (which seems to be hosted on Squarespace) would need to copy the VTT file over to the webserver. It now occurs to me that we can also link from the shownotes page to the VTT file here in the repo on GitHub, which means the VTT file doesn't necessarily have to exist on the webserver. This is probably easier.

**Comment by BasThomas** [comment]
Cc @JohnSundell 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by garricn** [comment]
> I'd like to add a link to the [transcript](https://github.com/SwiftCommunityPodcast/podcast/blob/master/Shownotes/Episode1-Transcript.vtt) ([now that it's merged](#43)) to the episode 1 shownotes. What URL do I have to use? How can we get the `.vtt` file on the webserver? What process do you use to build the website?

@ole John would know how to best do this in terms of what the ideal set up is but for now I will just link to the raw vtt file in the show notes.

**Comment by garricn** [comment]
@ole So I opened #52 and I already updated the actual episode on Squarespace. When this project picks up more steam I would love to clone the Swift Weekly Briefs style where the files in this repo actual feed a static site which would make keeping the show notes updated easier.

**Comment by BasThomas** [comment]
> I would love to clone the Swift Weekly Briefs style where the files in this repo actual feed a static site which would make keeping the show notes updated easier.

That'd be lovely! It was something I've been missing at the moment.

**Comment by ole** [comment]
@garricn Sounds good, thank you.
