### ISSUE TITLE
[WIP] [RFC] Episode Suggestion: State of The Community

### ISSUE THREAD

**Issue by mdiasdev** [SwiftCommunityPodcast/podcast#54]
# Keywords
- Community
- Episode

# Summary
There has been an interesting shift in the community. Where people used to gather around iOS or macOS as topics, everyone seems to have instead moved to all gather around Swift. I think it would be interesting to hear from a group of community builders and members about the state of the community, what it means to them, and how others can help keep up the spirit of building together.

**Suggested Co-Host Roles:**
- Content Creator (author, streamer, etc.)
- Community Organizer (meetup, user group, etc.)
- Community Member (someone who learned from community contribution)

# General Issue Information

**Comment by garricn** [comment]
Matt! Thank you for this suggestion issue. Have you considered opening an episode proposal PR? I am happy to be the “Review Manager”. I can help you produce the whole episode.

**Comment by JohnSundell** [comment]
I love this idea - let's turn it into an episode! 😀

**Comment by garricn** [comment]
Moved to PR #56
