### ISSUE TITLE
Provide email address for Code Of Conduct

### ISSUE THREAD

**Issue by jessesquires** [SwiftCommunityPodcast/podcast#55]
Per discussion in #49.

Opening this issue so this doesn't get lost.

cc @garricn @JohnSundell

**Comment by garricn** [comment]
Thank you for this @jessesquires . I'm looking into this. We can use my email address if needed but I'm trying to find out if we can have an email address for the podcast through our squarespace account.

**Comment by JohnSundell** [comment]
I'm happy for my email address to be used as well 👍

**Comment by JohnSundell** [comment]
@jessesquires you can use contact@swiftbysundell.com for the code of conduct 👍

**Comment by BasThomas** [comment]
Done in 2e144f

**Comment by jessesquires** [comment]
thanks @JohnSundell @BasThomas !

**Comment by BasThomas** [comment]
Thank _you_ for pushing this forward, @jessesquires 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
