### ISSUE TITLE
Contributing show notes and Squarespace site

### ISSUE THREAD

**Issue by MichaelNeas** [SwiftCommunityPodcast/podcast#61]
Hey!

Along similar lines of #27, is there a way for the community to help out with the Squarespace site or show note revisions?

![Screen Shot 2019-04-22 at 8 43 26 AM](https://user-images.githubusercontent.com/10774848/56501072-741a3200-64db-11e9-842f-955055fa726c.png)

"Result Type SE-0325" should be "Result Type [SE-0235](https://github.com/apple/swift-evolution/blob/master/proposals/0235-add-result.md)"

"SE-0240 Integer-convertible character literals" is "[SE-0243](https://github.com/apple/swift-evolution/blob/master/proposals/0243-codepoint-and-character-literals.md)"

Great job so far!

I look forward to more episodes 😄

**Comment by alexito4** [comment]
I wonder if it would be worth to build the website with some open source tooling and host it somewhere else that is integrated with GitHub. I really like Squarespace myself but I think that being able to PR into the website easily would be great. 

Unfortunately I don't know of any blog engine build in Swift yet, but I had much success with GatsbyJS + Netlify for hosting. I'm sure that audio hosting for a big podcast has more requirements, but it may be worth looking into it 😉

**Comment by MichaelNeas** [comment]
Closing this issue.

Hope the show picks back up some day!

Hope everyone stays healthy out there 😄

**Comment by alexito4** [comment]
I've been a bit disconnected from the podcast world but just to drop a comment here, since 2019 things have changed and now we have Publish so making a open source site hosted on github in pure swift is easier than ever :)
