### ISSUE TITLE
💡 Topic: Reactive Programming in Swift and Combine

### ISSUE THREAD

**Issue by LucianoPAlmeida** [SwiftCommunityPodcast/podcast#69]
# Keywords
- Swift
- Combine
- Reactive
- Rx

# Summary
Since episode 6 was `SwiftUI first impressions`, maybe we could have a `Combine first impressions` or something like a discussion around combine and the state of Reactive Programming in the  Swift Community (How people are using it with swift, what is the impact that Combine will have on the way we develop apps, and so on ...), also talk about  3rd party libraries like RxSwift and ReactiveCocoa too.

**Comment by BasThomas** [comment]
Cc @freak4pc. Interested?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by freak4pc** [comment]
Hello! 👋 
Sure, I have a bit of a tight schedule so might be tricky but I'm always down for some podcasts.

**Comment by JohnSundell** [comment]
Love this idea. Maybe @icanzilb wants to join too! Let me know how I can help to make this happen.

**Comment by icanzilb** [comment]
I’d love to if the date is rather soon, September will be quite crazy for me 😅 but as said - I’d love to!

**Comment by JohnSundell** [comment]
Awesome! I won't be able to personally drive this one, too many other things going on 😅, but I'd be happy to help out. As far as scheduling goes, we can do the episode whenever you want, we don't have any additional episodes in the works at the moment, so this'd be the perfect time to do it 👍

**Comment by icanzilb** [comment]
I can do Aug 21st in the evening EU time, eventually Aug 23rd. Not sure if @freak4pc could jump in as well? Then we'll have to adjust for his timezone a bit as well

**Comment by freak4pc** [comment]
Probably can :) I'm in GMT/UTC+3. If it doesn't work out and @icanzilb wants to do it alone that's also totally cool, sounds like fun though; if it works out I'd love to join

**Comment by icanzilb** [comment]
Great! How do we proceed about this?

**Comment by lattner** [comment]
I'm not competent to discuss UI development, but this sounds really interesting.  I'd recommend going deep if you can, e.g. talk about the rxswift features that Apple should learn from or something.  I'd start from a "we're assuming you already know what Combine/SwiftUI are" :-)

**Comment by LouisCAD** [comment]
If you're interested, I can talk about Flow in kotlinx.coroutines, which is a way to do reactive programming with suspending functions (i.e. coroutines in Kotlin), embracing cancellation ability.
I use it in Android development, and it can also be used on iOS and macOS with Kotlin/Native, despite interop with Swift not being ideal.

If coroutines eventually come to Swift, I think this is definitely an API to copy from kotlinx.coroutines.

**Comment by LucianoPAlmeida** [comment]
Hey :) 
Not sure if the episode has been recorded yet.
But maybe some good points to talk about could be:
* Could we expect combine support for non-Apple platforms? Could we expect one day take advantage of Combine on server-side applications running on Linux? 
* 3dr party frameworks adapting/supporting/creating bindings for working with Combine. One example is Moya recently released [Moya Combine support](https://github.com/Moya/Moya/releases/tag/14.0.0-beta.1) in beta.
* As @lattner metion go deep and talk about detailed design of the Combine (actually what you guys that have experience and have been using rxswift or any other reactive framework for some years think about the features of Combine), rxswift features that Apple should learn from (and vice-versa).
