### ISSUE TITLE
💡 Topic: The State of Swift on The Server

### ISSUE THREAD

**Issue by calebkleveter** [SwiftCommunityPodcast/podcast#70]
# Keywords
- Server
- Vapor
- Kitura
- NIO

# Summary
In less then 2 weeks, the [ServerSide.swift](https://www.serversideswift.info) conference will be happening in Copenhagen, DK. I thought this would be a great time to pull some people together from the community to discuss why we do Swift on the server, the current state of the frameworks, tools, and community, and where we want to see it go in the future.

**Comment by fassko** [comment]
I'm really looking forward to this episode, especially considering so much work has been put into latest version of Swift-NIO

**Comment by 0xTim** [comment]
I think we’re a go, there’s a Fireside Panel discussion already planned so the current plan is to record that as the podcast!

**Comment by JohnSundell** [comment]
Me and @0xTim spoke about this during Pragma Conference, and I'm really excited about this idea. So the plan is to make this Episode 7, and release it during November 😀

cc @lattner, @garricn

**Comment by BasThomas** [comment]
Looking forward to this one! Live podcasting is awesome 😎

**Comment by 0xTim** [comment]
This can now be closed! 🎉 

https://www.swiftcommunitypodcast.org/episodes/7
