### ISSUE TITLE
💡 Topic: Swift for Good

### ISSUE THREAD

**Issue by BasThomas** [SwiftCommunityPodcast/podcast#71]
I've been talking with @lattner and @twostraws to record an episode to cover Swift for Good, from the initial idea to the release of its first volume.

I'm not sure about the exact way to approach the episode yet, as that would also depend on those who would join the recording. @JohnSundell said he would consider joining the episode too.

Also, we'd love it if someone from the community could help produce the episode and allow us to release it! That would mean helping out with the [post production](https://github.com/SwiftCommunityPodcast/podcast/blob/master/CONTRIBUTING.md#post-production) as laid out in the Contributing guidelines.

As for a recording date: what about the weekend of February 1st? Either Saturday or Sunday works for me.

**Comment by AndrewLitteken** [comment]
I’d be happy to edit the episode again!

**Comment by twostraws** [comment]
Saturday 1st is fine for me – thanks for organizing!

**Comment by AndrewLitteken** [comment]
I don't think I will need to be on the recording since I will just be editing, but if I need to be, I will not be able to be on the call from 1 PM-7 PM CST on Saturday the 1st, but I am available at all other time.

**Comment by BasThomas** [comment]
You shouldn’t have to be, but we’ll let you know if we reschedule it from Paul’s suggestion!

**Comment by kcastellano** [comment]
I would love to join this episode 😄

**Comment by BasThomas** [comment]
As Chris is out of town we're postponing the recording until after February 10th

**Comment by BasThomas** [comment]
Alright, let's plan this @twostraws @kcastellano @lattner. Not sure what would be the best time with our timezones. Ideally we'd record somewhere between 5pm-11pm GMT+1; or earlier/later during the weekend. I would have time starting tomorrow.

**Comment by twostraws** [comment]
5pm-11pm on GMT+1 is fine for me too. I'm free tonight, Wednesday, Thursday, and Sunday, plus quite a few days next week.

**Comment by kcastellano** [comment]
5pm-11pm on GMT+1 works for me too. I'm free Thursday and Sunday and more flexible next week.

**Comment by lattner** [comment]
5pm on GMT+1 looks like it is 8am on pacific time.  For me, the best time would be Saturday or Sunday, Feb 15 or 16.  I can do any time 5-11pm on GMT on those days.

**Comment by BasThomas** [comment]
Then let me propose Sunday February 16, 5pm GMT. I'll send a Cast invite to all of you 👍

**Comment by JohnSundell** [comment]
Just a heads-up that this will be episode 8, since we just released [episode 7](https://www.swiftcommunitypodcast.org/episodes/7) about server-side Swift 🎉

**Comment by BasThomas** [comment]
Looking forward to this!

**Comment by BasThomas** [comment]
Hey @AndrewLitteken, we've just finished recording the episode. Is it ok if we send the audio files to the email on your GitHub profile?

**Comment by twostraws** [comment]
Here's the article from Ash: https://ashfurrow.com/blog/ios-versus-javascript-how-to-learn-from-other-programming-communities/

**Comment by AndrewLitteken** [comment]
Yes that’ll work great!

**Comment by twostraws** [comment]
And here's PyCon UK's page on diversity, inclusion, and accessibility: https://2019.pyconuk.org/diversity-inclusion-accessibility/

**Comment by kcastellano** [comment]
I think we should also add this :) https://www.hackingwithswift.com/live given that we spoke about it

**Comment by BasThomas** [comment]
I'll gladly compile the show notes 👍

**Comment by BasThomas** [comment]
This is expected to be published tomorrow. Thanks all again for the recording! :)

**Comment by lattner** [comment]
Awesome, looking forward to it.  Thank you!

**Comment by BasThomas** [comment]
https://www.swiftcommunitypodcast.org/episodes/8 🎉

**Comment by JohnSundell** [comment]
Announcement tweet: https://twitter.com/theswiftpodcast/status/1244626826586140678
