### ISSUE TITLE
Suggesting a guest: Ole Begemann

### ISSUE THREAD

**Issue by D4ttatraya** [SwiftCommunityPodcast/podcast#8]
As Ole is one of the people who follows Swift Evolution passionately, he can be a great guest on podcast to talk about evolution.
More about him: https://oleb.net/about/

**Comment by ole** [comment]
@D4ttatraya Thank you for thinking of me, I'm flattered. Never say never, but I'm currently not planning to appear on a podcast, sorry.

**Comment by D4ttatraya** [comment]
Never mind, but I hope that one day you will appear...
BTW, it's great that you replied 👍

**Comment by ole** [comment]
@D4ttatraya Could you please close this issue? Thanks.

**Comment by lattner** [comment]
Closing at @ole's request
